### ISSUE TITLE
Running test(s) throws KeyNotFoundException with newer Visual Studio 2022 update

### ISSUE THREAD

**Issue by PaulFocus** [JohnnyHendriks/TestAdapter_Catch2#68] opened 2023-03-22 20:36 UTC
test adapter: 1.8.0
catch2: 3.3.2
Visual Studio: 17.5.3

### what does not work

* selecting a single or multiple tests from the test explorer to run (see error below)

### what does work
* debugging a single test
* running all tests

### additional information
* problem started to occur after update of Visual Studio from 17.4.something to 17.5.3
* did run tests with catch2 3.3.2 before with the old VS version 

log:
```
Started Catch2Adapter test discovery...
Finished Catch2Adapter test discovery.
========== Testermittlung abgeschlossen: 814 Tests in "4,6 Sek." gefunden ==========
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_freeTask,,:7870c83f-0df1-c7ac-0f6a-6e12638f4285
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_requestStopTask invalid args,,:2647526f-69ab-91fa-d96d-9c600de709bb
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_requestStopTask abort script parsing,,:8f6e4b64-e153-874f-5b41-5928f0c81f58
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_isRunning invalid args,,:b4b03c62-5ca0-c5aa-b709-521c131ea446
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_freeTask,,:7870c83f-0df1-c7ac-0f6a-6e12638f4285
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
Erstellen von Test Projekten
========== Testlauf wird gestartet ==========
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_freeTask,,:7870c83f-0df1-c7ac-0f6a-6e12638f4285
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_freeTask,,:7870c83f-0df1-c7ac-0f6a-6e12638f4285
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_freeTask,,:7870c83f-0df1-c7ac-0f6a-6e12638f4285
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
Started Catch2Adapter test execution...
Finished Catch2Adapter test execution.
Fehler beim Hinzufügen des Ergebnisses für den Test "api.async.BCC_ASYNC_freeTask()" mit der ID "e87e91d8-7aa4-d3eb-35f3-ffc4ff465ff1".
========== Testlauf beendet: 1 Tests (1 erfolgreich, 0 fehlerhaft, 0 übersprungen) in 448 ms ausgeführt ==========
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_freeTask,,:7870c83f-0df1-c7ac-0f6a-6e12638f4285
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_freeTask,,:7870c83f-0df1-c7ac-0f6a-6e12638f4285
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
System.Collections.Generic.KeyNotFoundException: Unable to find UniqueTest VSTestAdapter,G:\code-review\bcc-1.7.0-weld\build\_deploy\test_d.exe,api.async.BCC_ASYNC_freeTask,,:7870c83f-0df1-c7ac-0f6a-6e12638f4285
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyNode.LookupUniqueTest(MergedTestIndex index)
   bei Microsoft.VisualStudio.TestStorage.TestStoreHierarchyIndex.<>c__DisplayClass50_0.<GetUniqueTestsForNodes>b__0(TestStoreHierarchyNode ct)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei Microsoft.VisualStudio.TestStorage.TestStore.<GetTestDetailsForNodes>d__138.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei Microsoft.VisualStudio.TestWindow.Host.TestWindowStoreService.<>c__DisplayClass50_0.<QueryTestDetailAsync>b__0()
   bei Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
```

**Comment by JohnnyHendriks** [comment] 2023-03-23 07:59
I'm afraid I'm not able to reproduce this. Only difference being that I used Catch2 v3.3.1, but that shouldn't make a difference in this case. The transition from VS 17.4 to 17.5 did not interfere with my ability to run the tests. Looks like something may have gone wrong with the Visual Studio Update process, unless it has something to do with being on a different language version of Visual Studio (I'm using an English version).

**Comment by JohnnyHendriks** [comment] 2023-03-28 19:32
Thanks for the info. I actually have unit tests for the test adapter that include `()` in the name. So the test adapter (and Catch2) seem to be fine with those names. So it really seems to be a problem with Visual Studio's Test Explorer. As such I will close this issue. But glad you were able to at least find a workaround for your problem.

**Closed by JohnnyHendriks** 2023-03-28 19:32 UTC
