### ISSUE TITLE
Test source (succsessfully discovered) is not navigatable with LLVM toolchain

### ISSUE THREAD

**Issue by tower120** [JohnnyHendriks/TestAdapter_Catch2#11] opened 2018-11-01 02:27 UTC
I'm not sure this is adapter fault, but:

When switching toolchain from MSVC_v141 (default) to LLVM (clang) double click on test does not opens test definition, and VS says "cannot locate xxxxx.cpp". With default Microsoft toolchain (v141) - everything fine.

**Comment by JohnnyHendriks** [comment] 2018-11-03 11:46
This indeed seems like a problem with the Test Explorer itself and not the adapter. The only thing I can think of is that when you switch toolchain, the information in the Test Explorer is no longer valid (even though it is still shown). Triggering a new test discovery (e.g. by closing the solution and then open it again, or by building one of the tests) may solve the problem.

I do not have my system setup to use a non-microsoft toolchains at this time, so I cannot reproduce your problem at this time. I will put it on my list of things to do. Still, based on your discription it seems to be a problem with the Test Explorer itself, so I will close this issue. I suggest you report this issue to the Visual Studio team via the bug report mechanism in Visual Studio.

**Closed by JohnnyHendriks** 2018-11-03 11:46 UTC

**Comment by tower120** [comment] 2018-11-04 03:46
Just FYI, LLVM on Windows now works out of the box.
You just have to install clang itself, and then install [this](https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.llvm-toolchain). Now you can switch toolchain in project properties to LLVM. And it works in any non-clr project.
