### ISSUE TITLE
Not working for me for visual studio 2019

### ISSUE THREAD

**Issue by snahmad** [JohnnyHendriks/TestAdapter_Catch2#24] opened 2019-05-14 14:15 UTC
14/05/2019 15:08:20 Informational] ------ Discover test started ------
[14/05/2019 15:08:20 Error] Failed to load RunSettings file: 'C:\Work\LibDev\UnitTests\ReferenceTests.runsettings'. Please check if the file exists and is valid.
[14/05/2019 15:08:20 Error] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)

**Comment by snahmad** [comment] 2019-05-14 21:55
Do we have minimal runsettings file I can use in VS2019 whiich shows test explorer.

**Comment by JohnnyHendriks** [comment] 2019-05-15 04:18
This looks like an error from Visual Studio Test Explorer, as these errors are not generated by the **Test Adapter for Catch2**. For an example of a minimal runsettings file see [Settings documentation](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Settings.md). Also the [Walkthrough page](https://github.com/JohnnyHendriks/TestAdapter_Catch2/blob/master/Docs/Walkthrough.md) may be helpful to solve problems setting up the test explorer.

Hope this helps to solve your problems.

**Comment by snahmad** [comment] 2019-05-15 13:03
Did you try yourself. I did try out a minimal runsettings file. still not working.

**Comment by JohnnyHendriks** [comment] 2019-05-15 22:25
This is really puzzling. I work with the **Test Adapter for Catch2** on almost a daily basis, both on VS2017 and VS2019. I double checked with the Solution file for the Test adapter (_i.e._, this GitHub repository) and also there everything works fine. So here some sanity checks to make sure we are on the same page.

- Is the latest version of the **Test Adapter for Catch2** extention installed (1.5.1)
- Are you working from a Visual Studio Solution (the test adapter does not work in combination with Open Folder/CMake mode).
- Try the tests in this repository in combination with the .runsettings files provided in this repository. This is proven to work.

If all still fails, this might have something to do with usage of alternate language versions of either Visual Studio or Windows. I only work and test on the English version, as such I would not notice problems caused by alternate language settings. But I'm grasping at straws here.

**Comment by JohnnyHendriks** [comment] 2021-03-13 15:55
Just released a new version (1.6.0), and am now going over open issues. The new version has a number of fixes and new features that should make usage more robust. Not sure if there is anything more I can do with regard to this issue, so I'm closing it.

**Closed by JohnnyHendriks** 2021-03-13 15:55 UTC
